Feature/arm
XaverianTeamRobotics/CenterstageFTCrobotcontroller pull request #582
Opened 2023-11-15 20:41 UTC by 28mpetrino

**Changes:**

This runs the arm, claw, and claw pivot.

**Controls and Usage:**

View the code for the controls.

**Reviewers:**

@XaverianTeamRobotics/senior-programmers

2023-11-15 21:24 UTC, MatthewL246 commented
@michaell4438 Should this be moved into a feature before merging? (Same with #583)

2023-11-15 21:25 UTC, michaell4438 commented
> @michaell4438 Should this be moved into a feature before merging? (Same with #583)

Probably.

2023-11-15 21:27 UTC, michaell4438 requested changes
Make this a feature

2023-11-15 21:27 UTC, MatthewL246 requested changes
Please move this code into a new feature (with a test opmode) before merging it into master. If you need help with that, Michael or I can help.

2023-11-15 21:28 UTC, MatthewL246 commented
Whoops both at the same time

2023-11-15 21:59 UTC, michaell4438 commented
https://robotics.xbhs.net/getting-started/Features

2023-11-15 22:08 UTC, MatthewL246 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/ArmClaw.java
> +public class ArmClaw extends OperationMode implements TeleOperation {
It's better to use the feature inside this opmode instead of copying the code.

2023-11-15 22:36 UTC, 28mpetrino commented
Yes,
Michael told me about this and it is being changed.
Thanks,
Marco Petrino

On Wed, Nov 15, 2023 at 5:09 PM Matthew Lopez ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/ArmClaw.java
> <https://github.com/XaverianTeamRobotics/FtcRobotController/pull/582#discussion_r1394887846>
> :
>
> > @@ -0,0 +1,68 @@
> +package org.firstinspires.ftc.teamcode.opmodes;
> +
> +import static org.firstinspires.ftc.teamcode.internals.hardware.Devices.motor2;
> +import static org.firstinspires.ftc.teamcode.internals.hardware.Devices.servo0;//this is the left grabber
> +import static org.firstinspires.ftc.teamcode.internals.hardware.Devices.servo1;//this is the right grabber
> +import static org.firstinspires.ftc.teamcode.internals.hardware.Devices.servo2;//this is the servo for the claw mechanism
> +
> +import org.firstinspires.ftc.teamcode.internals.hardware.Devices;//our two devices our the motors for the arm
> +import org.firstinspires.ftc.teamcode.internals.registration.OperationMode;
> +import org.firstinspires.ftc.teamcode.internals.registration.TeleOperation;
> +
> +public class ArmClaw extends OperationMode implements TeleOperation {
>
> It's better to use the feature inside this opmode instead of copying the
> code.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/XaverianTeamRobotics/FtcRobotController/pull/582#pullrequestreview-1733097974>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A43QMUCQI54D5UYZK5EAQETYEU4QJAVCNFSM6AAAAAA7NCXW3CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZTGA4TOOJXGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2023-11-16 00:10 UTC, michaell4438 requested changes

2023-11-16 00:10 UTC, michaell4438 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/features/ArmClaw.java
> +        servo2.setPosition(0);
It looks like this should be in the build function. Add `implements Buildable` after `extends Feature` then make a function named `build`. Look at the website [https://robotics.xbhs.net/getting-started/Features](https://robotics.xbhs.net/getting-started/Features) for an example.

2023-11-16 00:10 UTC, michaell4438 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/features/ArmClawIntake.java
You should probably delete this file. I don't know why it's here

2023-11-16 00:10 UTC, michaell4438 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/ArmClaw.java
Make this opmode use the feature

2023-11-16 00:12 UTC, MatthewL246 commented
@michaell4438 You can just click "Resolve conversation" instead of deleting my review.

2023-11-16 00:16 UTC, michaell4438 commented
> @michaell4438 You can just click "Resolve conversation" instead of deleting my review.

I still left you as reviewer, i just deleted a redundant comment

2023-11-16 00:50 UTC, michaell4438 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/features/ArmClawIntake.java
@28mpetrino still have to do this

2023-11-16 00:50 UTC, michaell4438 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/ArmClaw.java
@28mpetrino still have to do this

2023-11-16 01:49 UTC, michaell4438 commented
@28mpetrino there is still one file, features/ArmClawIntake which you need to delete

2023-11-16 02:08 UTC, MatthewL246 approved these changes
This looks all good to me now, thanks for addressing our feedback!

2023-11-16 02:28 UTC, michaell4438 approved these changes
lgtm

2023-11-16 02:29 UTC, merged